### ISSUE TITLE
Apple Silicon macOS Native client

### ISSUE THREAD

**Issue by danielktdoranie** [jhalter/mobius#113]
Hi, any hope for an Apple Silicon macOS Native client? I would love a server and client of course but a client alone would be amazing. Not a huge fan of running Intel code on my Apple Silicon M1 arm processor. Thanks!

**Comment by jhalter** [comment]
Oops, I thought I had that already, but it looks like I'm only building for Darwin amd64. I'll add it.

What installation method are you using?

**Comment by danielktdoranie** [comment]
A .dmg would be awesome. Thank you.

**Comment by jhalter** [comment]
I've modified the Homebrew formulas to build for Apple Silicon and added Apple Silicon as a build target for new versions in on the [releases](https://github.com/jhalter/mobius/releases) page.

To install with brew:
```
brew update
brew install jhalter/mobius-hotline-client/mobius-hotline-client
brew install jhalter/mobius-hotline-server/mobius-hotline-server
```

As you may be aware, distributing compiled binaries on modern macOS a pain as it requires going through Apple's notarization process, otherwise scary warnings block execution.  For this reason I recommend using the brew distribution on macOS, which avoids this by compiling the binaries on your system.  

But if you are anti-brew or just want the binaries for some reason, the latest Apple Silicon binaries are here:
https://github.com/jhalter/mobius/releases/download/v0.10.24/mobius_client_darwin_arm64.tar.gz
https://github.com/jhalter/mobius/releases/download/v0.10.24/mobius_server_darwin_arm64.tar.gz

I'm open to revisiting the dmg install method in the future, but not a layer of hell I want to revisit to at this time.

**Comment by danielktdoranie** [comment]
Hi @jhalter first off THANK YOU for doing this and also thanks for the amazingly quick reply. 

> As you may be aware, distributing compiled binaries on modern macOS a pain as it requires going through Apple's notarization process, otherwise scary warnings block execution.

Yeah it is annoying but it is easy to get around. Personally I despise Brew after having a bad experience with the people who run their Github page. I reported an issue with their `neofetch` repo and I got nothing but snark in reply. Personally I use [pkgsrc](https://pkgsrc.joyent.com/install-on-macos/).

Thank you for the .dmg files! I will save these and install both server and client! You're awesome!

**Comment by danielktdoranie** [comment]
Just a note to anyone who wants to install/run the client software above... unzip it (if Safari hasn't already unzipped it for you) open Terminal.app go to `/Downloads/dist/mobius_client_darwin_arm64` and run `sudo ./mobius-hotline-client -config ./mobius-client-config.yaml`

**Comment by jhalter** [comment]
Thanks for the feedback.  I haven't heard of [pkgsrc](https://pkgsrc.joyent.com/install-on-macos/) before.  If it's easy to contribute packages, I might be open to it.  Or is someone else wants to create and maintain a package even better. 😄

**Comment by aptonline** [comment]
Great to see Mobius getting updates 👍🏼
